### ISSUE TITLE
The example is too laggy

### ISSUE THREAD

**Issue by StanislavChankov** [tamani-coding/threejs-character-controls-example#1]

**Comment by jellehak** [comment]
I created a fork here https://github.com/jellehak/threejs-character-controls-example. 

Seems the floor is causing the issue. Better to use texture wrapping as shown here: https://github.com/jellehak/threejs-character-controls-example/blob/main/src/index.js#L96

**Comment by rudrakpatra** [comment]
YES ..    not calling  generateFloor()   makes the the example playable!

**Comment by tamani-coding** [comment]
I made the texture wrapping and repeating on one plane mesh, should be fine now
